[package]
name = "atc_cli"
version = "0.1.0"
edition = "2021"
description = "CLI-Tool for Kernel/Blockchain interaction"
authors = ["Michael Wroblewski"]
license = "Apache-2.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
atc-node = { git = "https://github.com/A-TownChain-Okosystems/atc-node", rev = "9b773e464f9d99e829003d087de157328c2cee8e" }
